name: Hello World Command
on:
  repository_dispatch:
    types: [hello-world-command]
jobs:
  dump-slash-command-payload: 
    name: 'Dump slash command payload for debugging purposes'
    runs-on: ubuntu-latest
    steps:
      - name: Dump the client payload context for debugging
        env:
          PAYLOAD_CONTEXT: ${{ toJson(github.event.client_payload) }}
        run: echo "$PAYLOAD_CONTEXT"

  branch-up-to-date:
    name: 'Is branch up-to-date?'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
#         with:
#           ref: ${{ github.event.client_payload.pull_request.head.sha }}

      - name: Checkout branches
        run: |
          git fetch --no-tags origin +refs/heads/*:refs/remotes/origin/*

      - name: Verify branch is up-to-date with master branch
        run: |
          if [ $(git log origin/${{ github.event.client_payload.pull_request.head.ref }}..origin/master --oneline | wc -l) -ne 0 ]
          then
            echo "Branch is not up-to-date with master branch!"
            exit 1
          fi

      - name: Comment on failure
        if: failure()
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.client_payload.pull_request.number }}
          token: ${{ secrets.GITHUB_TOKEN }}
          body: |
            Your branch is not up-to-date with `master`! Please rebase before proceeding.

  helloWorld:
    runs-on: ubuntu-latest
    needs: branch-up-to-date
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.event.client_payload.pull_request.head.sha }}

      - name: Add reaction
        uses: peter-evans/create-or-update-comment@v1
        with:
          comment-id: ${{ github.event.client_payload.github.payload.comment.id }}
          reaction-type: hooray

      - name: Create URL to the run output
        id: vars
        run: echo ::set-output name=run-url::https://github.com/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID
      
      - name: Add comment to PR
        uses: peter-evans/create-or-update-comment@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.client_payload.pull_request.number }}
          body: |
            HELLO WORLD ${{ github.event.client_payload.slash_command.args.unnamed.arg1 }}

            To teardown, comment with the `/teardown` command.

      - name: Create comment
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.client_payload.pull_request.number }}
          body: |
            Hello @${{ github.event.client_payload.github.actor }}!
            [Click here to see the command run output][1]
            [1]: ${{ steps.vars.outputs.run-url }}

