name: Hello World Command
on:
  repository_dispatch:
    types: [hello-world-command]
jobs:
  helloWorld:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.client_payload.pull_request.head.sha }}

      - name: Add reaction
        uses: peter-evans/create-or-update-comment@v1
        with:
          comment-id: ${{ github.event.client_payload.github.payload.comment.id }}
          reaction-type: hooray

      - name: Create URL to the run output
        id: vars
        run: echo ::set-output name=run-url::https://github.com/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID
      
      - name: Add comment to PR
        uses: peter-evans/create-or-update-comment@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.client_payload.pull_request.number }}
          body: |
            HELLO WORLD!!
            
            response: ${{ toJson(github.event.client_payload) }}

            To teardown, comment with the `/teardown` command.

#       - name: Create comment
#         uses: peter-evans/create-or-update-comment@v1
#         with:
#           issue-number: ${{ github.event.client_payload.github.payload.pu.number }}
#           body: |
#             Hello @${{ github.event.client_payload.github.actor }}!
#             [Click here to see the command run output][1]
#             [1]: ${{ steps.vars.outputs.run-url }}

